/* eslint-disable */
/*
 * AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by: npm run types:generate
 * Mode: remote
 * Schema: public
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "12.2.3 (519615d)"
  }
  public: {
    Tables: {
      _prisma_migrations: {
        Row: {
          applied_steps_count: number
          checksum: string
          finished_at: string | null
          id: string
          logs: string | null
          migration_name: string
          rolled_back_at: string | null
          started_at: string
        }
        Insert: {
          applied_steps_count?: number
          checksum: string
          finished_at?: string | null
          id: string
          logs?: string | null
          migration_name: string
          rolled_back_at?: string | null
          started_at?: string
        }
        Update: {
          applied_steps_count?: number
          checksum?: string
          finished_at?: string | null
          id?: string
          logs?: string | null
          migration_name?: string
          rolled_back_at?: string | null
          started_at?: string
        }
        Relationships: []
      }
      availability: {
        Row: {
          barber_id: string | null
          created_at: string | null
          day_of_week: number | null
          end_time: string
          id: string
          start_time: string
          updated_at: string | null
        }
        Insert: {
          barber_id?: string | null
          created_at?: string | null
          day_of_week?: number | null
          end_time: string
          id?: string
          start_time: string
          updated_at?: string | null
        }
        Update: {
          barber_id?: string | null
          created_at?: string | null
          day_of_week?: number | null
          end_time?: string
          id?: string
          start_time?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "availability_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      barbers: {
        Row: {
          average_rating: number | null
          bio: string | null
          business_name: string | null
          city: string | null
          created_at: string | null
          facebook: string | null
          id: string
          instagram: string | null
          is_developer: boolean | null
          latitude: number | null
          longitude: number | null
          next_available: string | null
          onboarding_complete: boolean | null
          portfolio: string[] | null
          price_range: string | null
          review_count: number | null
          specialties: string[] | null
          state: string | null
          status: string | null
          stripe_account_id: string | null
          stripe_account_ready: boolean | null
          stripe_account_status: string | null
          tiktok: string | null
          twitter: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          average_rating?: number | null
          bio?: string | null
          business_name?: string | null
          city?: string | null
          created_at?: string | null
          facebook?: string | null
          id?: string
          instagram?: string | null
          is_developer?: boolean | null
          latitude?: number | null
          longitude?: number | null
          next_available?: string | null
          onboarding_complete?: boolean | null
          portfolio?: string[] | null
          price_range?: string | null
          review_count?: number | null
          specialties?: string[] | null
          state?: string | null
          status?: string | null
          stripe_account_id?: string | null
          stripe_account_ready?: boolean | null
          stripe_account_status?: string | null
          tiktok?: string | null
          twitter?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          average_rating?: number | null
          bio?: string | null
          business_name?: string | null
          city?: string | null
          created_at?: string | null
          facebook?: string | null
          id?: string
          instagram?: string | null
          is_developer?: boolean | null
          latitude?: number | null
          longitude?: number | null
          next_available?: string | null
          onboarding_complete?: boolean | null
          portfolio?: string[] | null
          price_range?: string | null
          review_count?: number | null
          specialties?: string[] | null
          state?: string | null
          status?: string | null
          stripe_account_id?: string | null
          stripe_account_ready?: boolean | null
          stripe_account_status?: string | null
          tiktok?: string | null
          twitter?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "barbers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      blocked_users: {
        Row: {
          blocked_user_id: string
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          blocked_user_id: string
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          blocked_user_id?: string
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: []
      }
      booking_addons: {
        Row: {
          addon_id: string | null
          booking_id: string | null
          created_at: string | null
          id: string
          price: number
        }
        Insert: {
          addon_id?: string | null
          booking_id?: string | null
          created_at?: string | null
          id?: string
          price: number
        }
        Update: {
          addon_id?: string | null
          booking_id?: string | null
          created_at?: string | null
          id?: string
          price?: number
        }
        Relationships: [
          {
            foreignKeyName: "booking_addons_addon_id_fkey"
            columns: ["addon_id"]
            isOneToOne: false
            referencedRelation: "service_addons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "booking_addons_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      booking_restrictions: {
        Row: {
          advance_booking_days: number | null
          barber_id: string | null
          created_at: string | null
          id: string
          max_bookings_per_day: number | null
          min_interval_minutes: number | null
          same_day_booking_enabled: boolean | null
          updated_at: string | null
        }
        Insert: {
          advance_booking_days?: number | null
          barber_id?: string | null
          created_at?: string | null
          id?: string
          max_bookings_per_day?: number | null
          min_interval_minutes?: number | null
          same_day_booking_enabled?: boolean | null
          updated_at?: string | null
        }
        Update: {
          advance_booking_days?: number | null
          barber_id?: string | null
          created_at?: string | null
          id?: string
          max_bookings_per_day?: number | null
          min_interval_minutes?: number | null
          same_day_booking_enabled?: boolean | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "booking_restrictions_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: true
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      booking_texts: {
        Row: {
          barber_carrier: string | null
          barber_phone: string | null
          barber_sms_notifications: boolean | null
          booking_time: string | null
          client_carrier: string | null
          client_name: string | null
          client_phone: string | null
          client_sms_notifications: boolean | null
          confirmation_sent: boolean | null
          id: string
          reminder_sent: boolean | null
        }
        Insert: {
          barber_carrier?: string | null
          barber_phone?: string | null
          barber_sms_notifications?: boolean | null
          booking_time?: string | null
          client_carrier?: string | null
          client_name?: string | null
          client_phone?: string | null
          client_sms_notifications?: boolean | null
          confirmation_sent?: boolean | null
          id?: string
          reminder_sent?: boolean | null
        }
        Update: {
          barber_carrier?: string | null
          barber_phone?: string | null
          barber_sms_notifications?: boolean | null
          booking_time?: string | null
          client_carrier?: string | null
          client_name?: string | null
          client_phone?: string | null
          client_sms_notifications?: boolean | null
          confirmation_sent?: boolean | null
          id?: string
          reminder_sent?: boolean | null
        }
        Relationships: []
      }
      bookings: {
        Row: {
          addon_total: number | null
          barber_id: string
          barber_payout: number | null
          client_id: string | null
          created_at: string | null
          date: string
          end_time: string | null
          guest_email: string | null
          guest_name: string | null
          guest_phone: string | null
          id: string
          notes: string | null
          payment_intent_id: string | null
          payment_status: string | null
          platform_fee: number | null
          price: number
          review_requested: boolean | null
          review_requested_at: string | null
          service_id: string
          service_price: number | null
          status: string | null
          updated_at: string | null
        }
        Insert: {
          addon_total?: number | null
          barber_id: string
          barber_payout?: number | null
          client_id?: string | null
          created_at?: string | null
          date: string
          end_time?: string | null
          guest_email?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          id?: string
          notes?: string | null
          payment_intent_id?: string | null
          payment_status?: string | null
          platform_fee?: number | null
          price: number
          review_requested?: boolean | null
          review_requested_at?: string | null
          service_id: string
          service_price?: number | null
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          addon_total?: number | null
          barber_id?: string
          barber_payout?: number | null
          client_id?: string | null
          created_at?: string | null
          date?: string
          end_time?: string | null
          guest_email?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          id?: string
          notes?: string | null
          payment_intent_id?: string | null
          payment_status?: string | null
          platform_fee?: number | null
          price?: number
          review_requested?: boolean | null
          review_requested_at?: string | null
          service_id?: string
          service_price?: number | null
          status?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bookings_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      calendar_sync_logs: {
        Row: {
          connection_id: string | null
          created_at: string | null
          details: Json | null
          error_message: string | null
          id: string
          operation: string
          status: string
          user_id: string | null
        }
        Insert: {
          connection_id?: string | null
          created_at?: string | null
          details?: Json | null
          error_message?: string | null
          id?: string
          operation: string
          status: string
          user_id?: string | null
        }
        Update: {
          connection_id?: string | null
          created_at?: string | null
          details?: Json | null
          error_message?: string | null
          id?: string
          operation?: string
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "calendar_sync_logs_connection_id_fkey"
            columns: ["connection_id"]
            isOneToOne: false
            referencedRelation: "user_calendar_connections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "calendar_sync_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cut_analytics: {
        Row: {
          action_type: string | null
          created_at: string | null
          cut_id: string | null
          id: string
          ip_address: unknown
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          action_type?: string | null
          created_at?: string | null
          cut_id?: string | null
          id?: string
          ip_address?: unknown
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          action_type?: string | null
          created_at?: string | null
          cut_id?: string | null
          id?: string
          ip_address?: unknown
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cut_analytics_cut_id_fkey"
            columns: ["cut_id"]
            isOneToOne: false
            referencedRelation: "cuts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reel_analytics_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cut_comments: {
        Row: {
          comment: string
          created_at: string | null
          cut_id: string | null
          id: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          comment: string
          created_at?: string | null
          cut_id?: string | null
          id?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          comment?: string
          created_at?: string | null
          cut_id?: string | null
          id?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cut_comments_cut_id_fkey"
            columns: ["cut_id"]
            isOneToOne: false
            referencedRelation: "cuts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reel_comments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cuts: {
        Row: {
          barber_id: string | null
          category: string
          city: string | null
          comments_count: number | null
          country: string | null
          created_at: string | null
          description: string | null
          duration: number | null
          id: string
          is_featured: boolean | null
          is_public: boolean | null
          latitude: number | null
          likes: number | null
          location_name: string | null
          longitude: number | null
          shares: number | null
          state: string | null
          tags: string[] | null
          thumbnail: string | null
          title: string
          updated_at: string | null
          url: string
          views: number | null
        }
        Insert: {
          barber_id?: string | null
          category?: string
          city?: string | null
          comments_count?: number | null
          country?: string | null
          created_at?: string | null
          description?: string | null
          duration?: number | null
          id?: string
          is_featured?: boolean | null
          is_public?: boolean | null
          latitude?: number | null
          likes?: number | null
          location_name?: string | null
          longitude?: number | null
          shares?: number | null
          state?: string | null
          tags?: string[] | null
          thumbnail?: string | null
          title: string
          updated_at?: string | null
          url: string
          views?: number | null
        }
        Update: {
          barber_id?: string | null
          category?: string
          city?: string | null
          comments_count?: number | null
          country?: string | null
          created_at?: string | null
          description?: string | null
          duration?: number | null
          id?: string
          is_featured?: boolean | null
          is_public?: boolean | null
          latitude?: number | null
          likes?: number | null
          location_name?: string | null
          longitude?: number | null
          shares?: number | null
          state?: string | null
          tags?: string[] | null
          thumbnail?: string | null
          title?: string
          updated_at?: string | null
          url?: string
          views?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "reels_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          booking_id: string | null
          created_at: string | null
          id: string
          message: string
          read: boolean | null
          title: string
          type: string
          user_id: string | null
        }
        Insert: {
          booking_id?: string | null
          created_at?: string | null
          id?: string
          message: string
          read?: boolean | null
          title: string
          type: string
          user_id?: string | null
        }
        Update: {
          booking_id?: string | null
          created_at?: string | null
          id?: string
          message?: string
          read?: boolean | null
          title?: string
          type?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ondemand_requests: {
        Row: {
          barber_id: string | null
          client_id: string | null
          created_at: string | null
          id: string
          location_address: string | null
          location_lat: number | null
          location_lng: number | null
          notes: string | null
          price: number
          requested_time: string
          service_id: string | null
          status: string | null
          surge_multiplier: number | null
          updated_at: string | null
        }
        Insert: {
          barber_id?: string | null
          client_id?: string | null
          created_at?: string | null
          id?: string
          location_address?: string | null
          location_lat?: number | null
          location_lng?: number | null
          notes?: string | null
          price: number
          requested_time: string
          service_id?: string | null
          status?: string | null
          surge_multiplier?: number | null
          updated_at?: string | null
        }
        Update: {
          barber_id?: string | null
          client_id?: string | null
          created_at?: string | null
          id?: string
          location_address?: string | null
          location_lat?: number | null
          location_lng?: number | null
          notes?: string | null
          price?: number
          requested_time?: string
          service_id?: string | null
          status?: string | null
          surge_multiplier?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ondemand_requests_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ondemand_requests_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ondemand_requests_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      ondemand_settings: {
        Row: {
          availability_radius_miles: number | null
          barber_id: string | null
          created_at: string | null
          id: string
          is_enabled: boolean | null
          max_notice_hours: number | null
          min_notice_minutes: number | null
          surge_multiplier: number | null
          surge_pricing_enabled: boolean | null
          updated_at: string | null
        }
        Insert: {
          availability_radius_miles?: number | null
          barber_id?: string | null
          created_at?: string | null
          id?: string
          is_enabled?: boolean | null
          max_notice_hours?: number | null
          min_notice_minutes?: number | null
          surge_multiplier?: number | null
          surge_pricing_enabled?: boolean | null
          updated_at?: string | null
        }
        Update: {
          availability_radius_miles?: number | null
          barber_id?: string | null
          created_at?: string | null
          id?: string
          is_enabled?: boolean | null
          max_notice_hours?: number | null
          min_notice_minutes?: number | null
          surge_multiplier?: number | null
          surge_pricing_enabled?: boolean | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ondemand_settings_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: true
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount: number
          barber_stripe_account_id: string
          booking_id: string | null
          created_at: string
          currency: string
          id: string
          payment_intent_id: string
          platform_fee: number
          status: string
        }
        Insert: {
          amount: number
          barber_stripe_account_id: string
          booking_id?: string | null
          created_at: string
          currency: string
          id?: string
          payment_intent_id: string
          platform_fee: number
          status: string
        }
        Update: {
          amount?: number
          barber_stripe_account_id?: string
          booking_id?: string | null
          created_at?: string
          currency?: string
          id?: string
          payment_intent_id?: string
          platform_fee?: number
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          carrier: string | null
          coverphoto: string | null
          created_at: string | null
          description: string | null
          email: string | null
          email_notifications: boolean | null
          facebook_url: string | null
          favorites: string[] | null
          id: string
          instagram_url: string | null
          is_disabled: boolean | null
          is_public: boolean | null
          join_date: string | null
          location: string | null
          marketing_emails: boolean | null
          name: string | null
          phone: string | null
          role: string | null
          sms_notifications: boolean | null
          tiktok_url: string | null
          twitter_url: string | null
          updated_at: string | null
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          carrier?: string | null
          coverphoto?: string | null
          created_at?: string | null
          description?: string | null
          email?: string | null
          email_notifications?: boolean | null
          facebook_url?: string | null
          favorites?: string[] | null
          id: string
          instagram_url?: string | null
          is_disabled?: boolean | null
          is_public?: boolean | null
          join_date?: string | null
          location?: string | null
          marketing_emails?: boolean | null
          name?: string | null
          phone?: string | null
          role?: string | null
          sms_notifications?: boolean | null
          tiktok_url?: string | null
          twitter_url?: string | null
          updated_at?: string | null
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          carrier?: string | null
          coverphoto?: string | null
          created_at?: string | null
          description?: string | null
          email?: string | null
          email_notifications?: boolean | null
          facebook_url?: string | null
          favorites?: string[] | null
          id?: string
          instagram_url?: string | null
          is_disabled?: boolean | null
          is_public?: boolean | null
          join_date?: string | null
          location?: string | null
          marketing_emails?: boolean | null
          name?: string | null
          phone?: string | null
          role?: string | null
          sms_notifications?: boolean | null
          tiktok_url?: string | null
          twitter_url?: string | null
          updated_at?: string | null
          username?: string | null
        }
        Relationships: []
      }
      reports: {
        Row: {
          content_id: string
          content_type: string
          created_at: string
          description: string | null
          id: string
          reason: string
          reported_user_id: string | null
          reporter_id: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
          updated_at: string
        }
        Insert: {
          content_id: string
          content_type: string
          created_at?: string
          description?: string | null
          id?: string
          reason: string
          reported_user_id?: string | null
          reporter_id: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          content_id?: string
          content_type?: string
          created_at?: string
          description?: string | null
          id?: string
          reason?: string
          reported_user_id?: string | null
          reporter_id?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      reviews: {
        Row: {
          barber_id: string | null
          booking_id: string | null
          client_id: string | null
          comment: string | null
          created_at: string | null
          id: string
          is_moderated: boolean | null
          is_public: boolean | null
          is_verified: boolean | null
          moderator_notes: string | null
          rating: number
          updated_at: string | null
        }
        Insert: {
          barber_id?: string | null
          booking_id?: string | null
          client_id?: string | null
          comment?: string | null
          created_at?: string | null
          id?: string
          is_moderated?: boolean | null
          is_public?: boolean | null
          is_verified?: boolean | null
          moderator_notes?: string | null
          rating: number
          updated_at?: string | null
        }
        Update: {
          barber_id?: string | null
          booking_id?: string | null
          client_id?: string | null
          comment?: string | null
          created_at?: string | null
          id?: string
          is_moderated?: boolean | null
          is_public?: boolean | null
          is_verified?: boolean | null
          moderator_notes?: string | null
          rating?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: true
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      scheduling_slots: {
        Row: {
          barber_id: string | null
          buffer_minutes_after: number | null
          buffer_minutes_before: number | null
          created_at: string | null
          day_of_week: number | null
          end_time: string
          id: string
          is_active: boolean | null
          max_bookings_per_slot: number | null
          slot_duration_minutes: number | null
          start_time: string
          updated_at: string | null
        }
        Insert: {
          barber_id?: string | null
          buffer_minutes_after?: number | null
          buffer_minutes_before?: number | null
          created_at?: string | null
          day_of_week?: number | null
          end_time: string
          id?: string
          is_active?: boolean | null
          max_bookings_per_slot?: number | null
          slot_duration_minutes?: number | null
          start_time: string
          updated_at?: string | null
        }
        Update: {
          barber_id?: string | null
          buffer_minutes_after?: number | null
          buffer_minutes_before?: number | null
          created_at?: string | null
          day_of_week?: number | null
          end_time?: string
          id?: string
          is_active?: boolean | null
          max_bookings_per_slot?: number | null
          slot_duration_minutes?: number | null
          start_time?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "scheduling_slots_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      service_addons: {
        Row: {
          barber_id: string | null
          created_at: string | null
          description: string | null
          id: string
          is_active: boolean | null
          name: string
          price: number
          updated_at: string | null
        }
        Insert: {
          barber_id?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          price: number
          updated_at?: string | null
        }
        Update: {
          barber_id?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          price?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "service_addons_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      services: {
        Row: {
          barber_id: string | null
          created_at: string | null
          description: string | null
          duration: number
          id: string
          name: string
          price: number
          updated_at: string | null
        }
        Insert: {
          barber_id?: string | null
          created_at?: string | null
          description?: string | null
          duration: number
          id?: string
          name: string
          price: number
          updated_at?: string | null
        }
        Update: {
          barber_id?: string | null
          created_at?: string | null
          description?: string | null
          duration?: number
          id?: string
          name?: string
          price?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "services_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      special_hours: {
        Row: {
          barber_id: string | null
          created_at: string | null
          date: string
          end_time: string
          id: string
          is_closed: boolean | null
          reason: string | null
          start_time: string
          updated_at: string | null
        }
        Insert: {
          barber_id?: string | null
          created_at?: string | null
          date: string
          end_time: string
          id?: string
          is_closed?: boolean | null
          reason?: string | null
          start_time: string
          updated_at?: string | null
        }
        Update: {
          barber_id?: string | null
          created_at?: string | null
          date?: string
          end_time?: string
          id?: string
          is_closed?: boolean | null
          reason?: string | null
          start_time?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "special_hours_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      synced_events: {
        Row: {
          booking_id: string | null
          created_at: string | null
          event_data: Json | null
          external_calendar_id: string
          external_event_id: string
          id: string
          last_synced_at: string | null
          sync_direction: string | null
          sync_status: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          booking_id?: string | null
          created_at?: string | null
          event_data?: Json | null
          external_calendar_id: string
          external_event_id: string
          id?: string
          last_synced_at?: string | null
          sync_direction?: string | null
          sync_status?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          booking_id?: string | null
          created_at?: string | null
          event_data?: Json | null
          external_calendar_id?: string
          external_event_id?: string
          id?: string
          last_synced_at?: string | null
          sync_direction?: string | null
          sync_status?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "synced_events_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "synced_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      time_off: {
        Row: {
          barber_id: string | null
          created_at: string | null
          end_date: string
          id: string
          reason: string | null
          start_date: string
          updated_at: string | null
        }
        Insert: {
          barber_id?: string | null
          created_at?: string | null
          end_date: string
          id?: string
          reason?: string | null
          start_date: string
          updated_at?: string | null
        }
        Update: {
          barber_id?: string | null
          created_at?: string | null
          end_date?: string
          id?: string
          reason?: string | null
          start_date?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "time_off_barber_id_fkey"
            columns: ["barber_id"]
            isOneToOne: false
            referencedRelation: "barbers"
            referencedColumns: ["id"]
          },
        ]
      }
      user_calendar_connections: {
        Row: {
          access_token: string
          calendar_id: string | null
          created_at: string | null
          expires_at: string | null
          id: string
          last_sync_at: string | null
          provider: string
          refresh_token: string | null
          sync_direction: string | null
          sync_enabled: boolean | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          access_token: string
          calendar_id?: string | null
          created_at?: string | null
          expires_at?: string | null
          id?: string
          last_sync_at?: string | null
          provider: string
          refresh_token?: string | null
          sync_direction?: string | null
          sync_enabled?: boolean | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          access_token?: string
          calendar_id?: string | null
          created_at?: string | null
          expires_at?: string | null
          id?: string
          last_sync_at?: string | null
          provider?: string
          refresh_token?: string | null
          sync_direction?: string | null
          sync_enabled?: boolean | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_calendar_connections_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      acquire_booking_slot_lock: {
        Args: { p_barber_id: string; p_date: string }
        Returns: boolean
      }
      expire_ondemand_requests: { Args: never; Returns: undefined }
      get_profile_by_username: {
        Args: { username_param: string }
        Returns: {
          avatar_url: string | null
          bio: string | null
          carrier: string | null
          coverphoto: string | null
          created_at: string | null
          description: string | null
          email: string | null
          email_notifications: boolean | null
          facebook_url: string | null
          favorites: string[] | null
          id: string
          instagram_url: string | null
          is_disabled: boolean | null
          is_public: boolean | null
          join_date: string | null
          location: string | null
          marketing_emails: boolean | null
          name: string | null
          phone: string | null
          role: string | null
          sms_notifications: boolean | null
          tiktok_url: string | null
          twitter_url: string | null
          updated_at: string | null
          username: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "profiles"
          isOneToOne: false
          isSetofReturn: true
        }
      }
    }
    Enums: {
      BookingStatus:
        | "PENDING"
        | "CONFIRMED"
        | "CANCELLED"
        | "COMPLETED"
        | "NO_SHOW"
      PaymentStatus: "PENDING" | "PAID" | "REFUNDED" | "FAILED"
      UserRole: "CLIENT" | "BARBER"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      BookingStatus: [
        "PENDING",
        "CONFIRMED",
        "CANCELLED",
        "COMPLETED",
        "NO_SHOW",
      ],
      PaymentStatus: ["PENDING", "PAID", "REFUNDED", "FAILED"],
      UserRole: ["CLIENT", "BARBER"],
    },
  },
} as const
