import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

type Mode = "local" | "remote";

function loadDotEnvIfPresent() {
  // Important: `npm run ...` does NOT automatically load `.env` for Node scripts.
  // Next.js loads `.env*` for the app runtime, but this generator is a standalone script.
  // So we load `.env` ourselves (only filling in missing keys).
  const envPath = path.resolve(process.cwd(), ".env");
  if (!fs.existsSync(envPath)) return;

  const raw = fs.readFileSync(envPath, "utf8");
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;

    const key = trimmed.slice(0, eq).trim();
    if (!key) continue;
    if (process.env[key] !== undefined) continue; // never override real env

    let value = trimmed.slice(eq + 1).trim();
    // Strip surrounding quotes if present.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    process.env[key] = value;
  }
}

function readMode(): Mode {
  // Prefer explicit CLI arg, then env var.
  const argv = process.argv.slice(2);
  const argMode = argv.find((a) => a === "--local" || a === "--remote");
  if (argMode === "--local") return "local";
  if (argMode === "--remote") return "remote";

  const envMode = (process.env.SUPABASE_GEN_MODE || "").toLowerCase();
  if (envMode === "local") return "local";
  if (envMode === "remote") return "remote";

  // Default to remote since it doesn't require Docker, only a Supabase project ref + token.
  return "remote";
}

function readProjectRef(): string {
  // Commonly used names in docs/scripts; accept any of them.
  return (
    process.env.PROJECT_REF ||
    process.env.SUPABASE_PROJECT_REF ||
    process.env.SUPABASE_PROJECT_ID ||
    ""
  );
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function main() {
  loadDotEnvIfPresent();
  const mode = readMode();

  // Keep path stable so imports don't churn.
  const outFile = path.resolve(
    process.cwd(),
    "packages/shared/src/types/database.ts"
  );
  ensureDir(path.dirname(outFile));

  // Supabase CLI supports skipping `supabase login` when SUPABASE_ACCESS_TOKEN is set.
  // See: https://supabase.com/docs/reference/cli/supabase-login
  const env = { ...process.env };

  const cli = "npx";
  const cliBaseArgs = ["--yes", "supabase", "gen", "types", "typescript"];
  const schemaArgs = ["--schema", "public"];

  let cmdArgs: string[] = [];
  if (mode === "local") {
    // Requires local Supabase stack running (Docker) via `supabase start`.
    cmdArgs = [...cliBaseArgs, "--local", ...schemaArgs];
  } else {
    const projectRef = readProjectRef();
    if (!projectRef) {
      throw new Error(
        [
          "Missing Supabase project ref for type generation.",
          "Set one of: PROJECT_REF, SUPABASE_PROJECT_REF, SUPABASE_PROJECT_ID.",
          "Then run: npm run types:generate",
          "",
          "Alternatively run locally (requires Docker):",
          "  SUPABASE_GEN_MODE=local npm run types:generate",
        ].join("\n")
      );
    }

    cmdArgs = [...cliBaseArgs, "--project-id", projectRef, ...schemaArgs];
  }

  const stdout = execFileSync(cli, cmdArgs, {
    env,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
  });

  const header = [
    "/* eslint-disable */",
    "/*",
    " * AUTO-GENERATED FILE. DO NOT EDIT.",
    " *",
    ` * Generated by: npm run types:generate`,
    ` * Mode: ${mode}`,
    ` * Schema: public`,
    " */",
    "",
  ].join("\n");

  fs.writeFileSync(outFile, header + stdout, "utf8");
  // eslint-disable-next-line no-console
  console.log(`✅ Wrote Supabase types to: ${outFile}`);
}

main();

